//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess2
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Customers")] // Ensure the table matches the pluralized name
    public partial class Customer
    {
        public Customer()
        {
            Orders = new HashSet<Order>();
        }

        [Key]
        public int CustomerID { get; set; }

        [Required]
        [MaxLength(100)] // Example constraint for Name
        public string Name { get; set; }

        [MaxLength(150)] // Example constraint for ContactInfo
        public string ContactInfo { get; set; }

        [MaxLength(250)] // Example constraint for Address
        public string Address { get; set; }

        public int? LoyaltyPoints { get; set; }

        public DateTime? LastModified { get; set; }

        public virtual ICollection<Order> Orders { get; set; }
    }
}
