//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess2
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Employees")] // Ensure the table matches the pluralized name
    public partial class Employee
    {
        public Employee()
        {
            Inventories = new HashSet<Inventory>();
            Orders = new HashSet<Order>();
            Shipments = new HashSet<Shipment>();
        }

        [Key]
        public int EmployeeID { get; set; }

        [Required]
        [MaxLength(100)] // Example constraint for Name
        public string Name { get; set; }

        [MaxLength(50)] // Example constraint for Role
        public string Role { get; set; }

        [MaxLength(150)] // Example constraint for ContactInfo
        public string ContactInfo { get; set; }

        public DateTime? LastModified { get; set; }

        public virtual ICollection<Inventory> Inventories { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Shipment> Shipments { get; set; }
    }
}
