//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess2
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Orders")] // Ensure the table matches the pluralized name
    public partial class Order
    {
        public Order()
        {
            OrderDetails = new HashSet<OrderDetail>();
            Shipments = new HashSet<Shipment>();
        }

        [Key]
        public int OrderID { get; set; }

        [Required]
        public int CustomerID { get; set; }

        public int? EmployeeID { get; set; }

        [Required]
        public DateTime OrderDate { get; set; }

        public decimal? TotalAmount { get; set; }

        public DateTime? LastModified { get; set; }

        // Navigation properties
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }

        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<Shipment> Shipments { get; set; }
    }
}
