//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess2
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Products")] // Ensure the table matches the pluralized name
    public partial class Product
    {
        public Product()
        {
            Inventories = new HashSet<Inventory>();
            OrderDetails = new HashSet<OrderDetail>();
            PromotionalOffers = new HashSet<PromotionalOffer>();
            SupplierProducts = new HashSet<SupplierProduct>();
        }

        [Key]
        public int ProductID { get; set; }

        [Required]
        [MaxLength(100)] // Example constraint for Name
        public string Name { get; set; }

        [MaxLength(50)] // Example constraint for Brand
        public string Brand { get; set; }

        [MaxLength(50)] // Example constraint for Flavor
        public string Flavor { get; set; }

        [MaxLength(50)] // Example constraint for PackSize
        public string PackSize { get; set; }

        [Required]
        [Range(0.01, double.MaxValue, ErrorMessage = "Price must be greater than 0.")]
        public decimal Price { get; set; }

        public DateTime? LastModified { get; set; }

        // Navigation properties
        public virtual ICollection<Inventory> Inventories { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<PromotionalOffer> PromotionalOffers { get; set; }
        public virtual ICollection<SupplierProduct> SupplierProducts { get; set; }
    }
}
