//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess2
{
    using System;
    using System.ComponentModel.DataAnnotations;

    public partial class PromotionalOffer
    {
        [Key]
        public int OfferID { get; set; }
        public int ProductID { get; set; }
        public decimal? DiscountRate { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public DateTime? LastModified { get; set; }

        public virtual Product Product { get; set; }
    }

}
