//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess2
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Shipments")] // Ensure the table matches the pluralized name
    public partial class Shipment
    {
        [Key]
        public int ShipmentID { get; set; }

        [Required]
        public int OrderID { get; set; }

        public int? EmployeeID { get; set; }

        [Required]
        public DateTime ShipmentDate { get; set; }

        public DateTime? EstimatedDeliveryDate { get; set; }

        public DateTime? LastModified { get; set; }

        // Navigation properties
        public virtual Employee Employee { get; set; }
        public virtual Order Order { get; set; }
    }
}
